<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-01 at 11:22:11.
 */
/**
* @backupGlobals disabled
* @backupStaticAttributes disabled
*/
require_once __DIR__ . '/../../class/Users.php';
require_once __DIR__ . '/../../class/Db.php';
class UsersTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Users
     */
    protected $user;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $db = new Db();
        $this->user = new Users($db);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
       unset($this->user);
    }

    /**
     * @covers Users::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        $this->user->login('jen@gmail.com', 'imthedemon0');
        $this->assertEquals($this->user->getEmail(),'jen@gmail.com');
    }
    
    public function testIsLoggedIn(){
        //$this->user->logout();
        $this->assertEquals($this->user->sessionCheck(),true);
    }
    
    /*
     * @todo Implement logout function
     * 
     */
    
    public function testLogout(){
        $this->user->logout();
        $this->assertEquals($this->user->sessionCheck(),false);
    }
    
    /*
     * @todo Implement the register function 
     */
    public function testRegister(){
     
     $this->assertEquals($this->user->register('Akshat', 'jen@gmail.com', 'ajen', 'different'),false);
    }

    

}
